name: Build and Release

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'  # Push events to matching v*, i.e. v1.0, v20.15.10
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # This is required for creating releases

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest]  # You can add more OS if needed: macos-latest, ubuntu-latest
        python-version: ["3.12"]
        
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pyinstaller
        pip install -r requirements.txt
        
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Build with PyInstaller
      run: |
        python build.py
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: AI-Cluster-Evaluator-${{ matrix.os }}
        path: dist/AI集群评测系统.exe
        
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: softprops/action-gh-release@v1
      with:
        files: dist/AI集群评测系统.exe
        name: Release ${{ github.ref_name }}
        draft: false
        prerelease: false
        token: ${{ secrets.RELEASE_TOKEN }}